# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the AWS CLI
RUN apt-get update && apt-get install -y awscli

USER root

# Download and install the AWS SAM CLI
RUN curl -L -o /tmp/aws-sam-cli-linux-x86_64.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip && \
    unzip /tmp/aws-sam-cli-linux-x86_64.zip -d /tmp/sam  && chmod +x /tmp/sam/install && \
    /tmp/sam/install


# # Install your Python requirements
RUN pip install -r ./layer/requirements.txt