version: '3'
services:
  python_container:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: tail -f /dev/null
  # localstack:
  #   image: localstack/localstack:2.3.2
  #   container_name: localstack
  #   environment:
  #     - SERVICES=lambda
  #     - DEFAULT_REGION=us-east-1
  #     - HOSTNAME=localhost
  #     - AWS_ACCESS_KEY_ID=localstack
  #     - AWS_SECRET_ACCESS_KEY=localstack
  #   ports:
  #     - "4566:4566"  